### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiohttp-devtools#147]
Currently aiohttp-devtools doesn't work with aiohttp 2.3.0 so we need to fix this ASAP and do a new release.

The only definite problem I know about is `finish_connections` vs `shutdown` which is fixed in #144.

It would also be good to merge #145, that's quite simple but it would be good to be sure it fixed the problem and also that it doesn't do anything terrible on OSX / windows - I have no idea how terminal stdin file descriptors work there.

@asvetlov do you want to review either of those PRs or just code before release?

**Comment by asvetlov** [comment]
On my way!

**Comment by samuelcolvin** [comment]
DONE.
