### ISSUE TITLE
Problem with library yarl v1.0

### ISSUE THREAD

**Issue by Kazun3500** [aio-libs/aiohttp-devtools#166]
* **aiohttp-devtools version:**
0.6.4
* **aiohttp version:**
2.3.8
* **yarl library version:**
1.0
* **python version:**
3.6.1
* **Platform:**
Linux Ubuntu 16.04
### Issue Summary
aiohttp-devtools don't work with yarl library version 1.0.
Reason - https://github.com/aio-libs/aiohttp-devtools/blob/33ef2dc75a30264fe26bdaf69ea3c6d0fbc9a62b/aiohttp_devtools/runserver/serve.py#L15 (at least). I don't check all files, maybe there are any other places with similar error.

**Comment by asvetlov** [comment]
Duplicate for #165
