### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-devtools#172]
`see HISTORY.rst` is not very informative.
Could you please add a link to release notes at least?
Ideally change notes from the release should be copied to text area but the link is required at least.

**Comment by samuelcolvin** [comment]
Will do. 

Where did you see this? https://pyup.io/changelogs/aiohttp-devtools/ correctly showed the changes from history.rst

**Comment by samuelcolvin** [comment]
updated with changes back to v0.4.

Will do properly from now on.

**Comment by asvetlov** [comment]
Thanks.
I've subscribed on github changes and receive a notification  email on every release. The message text is not very informative
