### ISSUE TITLE
steps in tutorial doesnt work on Windows

### ISSUE THREAD

**Issue by tyoc213** [aio-libs/aiohttp-devtools#179]
* **aiohttp-devtools version:**
aiodns (1.1.1)
aiohttp-debugtoolbar (0.5.0)
aiohttp-devtools (0.8)
aiohttp-jinja2 (0.15.0)
aiohttp-session (2.2.0)
* **aiohttp version:**

aiohttp (3.0.1)
* **python version:**
Python 3.6.0 :: Anaconda 4.3.1 (64-bit)
* **Platform:**
Windows 10

### Issue Summary
The steps in the tutorial doesnt launch and gives this error

```
C:\Users\tyoc213\my_new_app>adev runserver
Error: unable to find a recognised default file ("app.py" or "main.py") in the directory "."
```
after that I added the variables in `activate.settings.sh` like

```
setx AIO_APP_PATH "./app/"
setx AIO_STATIC_PATH "./static/"
```
(I also did try without the `./`)

And now I get 

```
C:\Users\tyoc213\my_new_app>adev runserver
Error: error importing "app\main" from "C:\Users\tyoc213\my_new_app": No module named 'app\\main'
```

There is a main.py inside

![imagen](https://user-images.githubusercontent.com/506234/37248534-8acb3a76-249a-11e8-8d38-7f6249f74262.png)

### Steps to reproduce

Follow the steps in the tutorial without changing to virtual env because Im already running on anaconda.

**Comment by mattpropdata** [comment]
I've seen this error. Your pathing is wrong. Ensure that your environment is correct (esp. AIO_APP_PATH) and it will work. Windows may use different pathing conventions (ie. \ instead of /).

I hope this helps.

**Comment by samuelcolvin** [comment]
Thanks @mootoom.

I'm closing this. I don't run windows so can't really help with errors like this.
