### ISSUE TITLE
Update all `secret: ` values in `.travis.yml`

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiohttp-devtools#192]
Do like this:
```
REPO_NAME={{ YOUR_REPO_NAME }}
travis encrypt -r "aio-libs/${REPO_NAME}" --api-endpoint 'https://api.travis-ci.com/'
```

Ref: https://github.com/orgs/aio-libs/teams/admins/discussions/9

**Comment by samuelcolvin** [comment]
Thanks a lot, updated that now. I'll deploy and check it works.

**Comment by webknjaz** [comment]
Oh btw you can separate deploy into `jobs.include` with `stage: deploy` and `if: tag IS present` to make it run after all test jobs in a separate job.

**Comment by samuelcolvin** [comment]
still failing https://travis-ci.com/aio-libs/aiohttp-devtools/jobs/127943366

Do I need to use a script and deploy manually?

**Comment by webknjaz** [comment]
Are you sure you used correct username and password and did all travis CLI commands with `--api-endpoint 'https://api.travis-ci.com/'`?

Sometimes it happens to me that it adds extra LF or so when I enter data for encryption. Have you tried rerunning it?

The approach described in the description proved to be working for other repos.

**Comment by samuelcolvin** [comment]
worked at last. thank you. I think the problem was that (contrary to their docs

    travis encrypt -r "aio-libs/aiohttp-devtools" --api-endpoint 'https://api.travis-ci.com/' deploy.password=mypassword

Doesn't work and in fact encrypts `deploy.password=mypassword` not just `mypassword`.

**Comment by webknjaz** [comment]
oh, you are probably confusing `--add deploy.password`, do you?

**Comment by webknjaz** [comment]
It's documented correctly: https://docs.travis-ci.com/user/environment-variables#Encrypting-environment-variables
You've probably misremembered the syntax.

**Comment by samuelcolvin** [comment]
The `MY_SECRET_ENV=super_secret` confused me. But no problem, fixed now.

**Comment by samuelcolvin** [comment]
fine by me, how do I give another user access to the project or transfer it?

**Comment by webknjaz** [comment]
Go to https://pypi.org/manage/project/aiohttp-devtools/collaboration/ and add `aio-libs-bot` as `Maintainer` (not `Owner`!). We need to maintain as restricted privileges as possible for bot accounts.

**Comment by samuelcolvin** [comment]
done.

**Comment by webknjaz** [comment]
Now, you can change the password to
```yaml
secure: >-
  pAzJhAD5HNzxvbNg/UwquwPXOp6V27gi4MpqCs6mK2Hy9h3Ii8vVWzEUx06v2aqT5b3P7FDBRW8+t9oL+aS/dZxeOtA/jNzROxMhFtRbpv1F/Mvd6ocz7yb3yg9WUlc7bhuyN6GUxsw4esATElQygqZucXRGsg+yauiTTd2X1CK6zrTz7/5lhF5H41oMzBKBZgvEUjDzaTs+C+B0bEifADVsI8QDa4EUTzCc93qf2z1jllDd/Jww9MK6xdBJJCoXjfBtWSjnoBANN/Ikthy8yY2PXvbLKH7K4Ri+ED72tLXThuTEsmquj20TnR30Hpm0LjwfdZ1+2O0X0PMyjMIRoATR0D9XdSP36FZs19zyRRFwHYKxZvXKSv+rZxz1rZYbbPojNW/498zlWcI8R9TxqPg/6dnrO1StnltLmN784AVBQr172CX/Ji3BF1bVytgdKqstGVN6d1JJWPuFVNfGpVHJJZEEuOBndK7yoSSV4zMva5wXplETVyGWfPiqvQCtylq8IatXbFxA0trCMW1kQEwBMBLbYrqx6ZIHQJ4Z46ng7OIYdRPod7fkK7e0lXU7OexfXad/UOWfkayOG1C93MWxeVho8ZQrBCdrHd1a5iujAfW8pk7Al8f2gS8L7nZTXUlkWK2ppX9PDOv1O0frtFc1prje+9AzROFC8UXxJk8=
```
in travis config (and change the user to aio-libs-bot)

**Comment by samuelcolvin** [comment]
please review #239.
