### ISSUE TITLE
Debug toolbar don't work by default.

### ISSUE THREAD

**Issue by Arfey** [aio-libs/aiohttp-devtools#200]
What we need to solve in `debugtoolbar` for removing this todo?

https://github.com/aio-libs/aiohttp-devtools/blob/ec1da745a8a74d4623a85d4b2b02241ca4f0938a/aiohttp_devtools/runserver/config.py#L38
I wanna solve that but i don't know what 😅

**Comment by samuelcolvin** [comment]
Debug-toolbar is basically abandoned, and it's a mess, a port of a port
which really needs a big rethink and a new front end.

It should be removed from devtools.

**Comment by Arfey** [comment]
Ok, thx. I think will be better if we remove that point from the doc.

```
a debug toolbar is automatically enabled using aiohttp debugtoolbar.
```

**Comment by samuelcolvin** [comment]
yes. PR welcome.

**Comment by samuelcolvin** [comment]
closing this, but I'll remove debugtool completely when I get a chance.

**Comment by samuelcolvin** [comment]
I've waited a year...
