### ISSUE TITLE
Server reload, custom port and host

### ISSUE THREAD

**Issue by dmytrostriletskyi** [aio-libs/aiohttp-devtools#205]
* **aiohttp-devtools version:** 0.10.1
* **aiohttp version:** 3.4.2
* **python version:** 3.5.4rc1
* **Platform:** MacOS

### Issue Summary

Cannot run server on the specified host and port. Also server does not reload self after changes.

### Steps to reproduce

`adev runserver --port=8000` or `adev runserver --port 8000` (the same with host).

**Comment by webknjaz** [comment]
"cannot run" doesn't add any clarity to what you're trying to run.

**Comment by dmytrostriletskyi** [comment]
@webknjaz, after `adev runserver --port=8000` or `adev runserver --port 8000`, `adev` runs server on port `8080` and show:

```
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
```

Also if I change code, server do not wanna to reload.

**Comment by dmytrostriletskyi** [comment]
@webknjaz, even code paste from [aiohttp quickstart](https://aiohttp.readthedocs.io/en/stable/web_quickstart.html#web-server-quickstart):

```python
from aiohttp import web

async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(text=text)

app = web.Application()
app.add_routes([web.get('/', handle),
                web.get('/{name}', handle)])

web.run_app(app)
```

**Comment by jamesward** [comment]
I ran into this as well.  I think the problem is that `web.run_app(...)` blocks the dev server from starting.  So I split the app into two parts, one that can be reloaded (in an `app.py` file):
```
async def create_app():
    app = web.Application()
    app.router.add_get('/', handle)
    return app
```

And one that can be used outside of `adev runserver` (in a `server.py` file):
```
web.run_app(app.create_app(), port=port)
```

Now I can do either `adev runserver` or `python server.py` and it all seems to work.

**Comment by valentim** [comment]
@jamesward thank you very much

**Comment by Dreamsorcerer** [comment]
This is mentioned in the README, `web.run_app()` shouldn't be called under `if __name__ == '__main__'` or similar, so it is not run when simply importing the module.
