### ISSUE TITLE
reload not working on non standard project structure

### ISSUE THREAD

**Issue by idwaker** [aio-libs/aiohttp-devtools#209]
* **aiohttp-devtools version:**
0.10.3

* **aiohttp version:**
3.4.4

* **python version:**
3.6

* **Platform:**
Solus Linux

### Issue Summary
I am using DDD structure for current project with separate **application** and **webapi** entry point. devtools doesnot use root path as project folder rather uses app_path which in this case unable watch changes on files inside application directory.

### Steps to reproduce

1. Create entry app entry point on separate directory from application directory

- webapp/
  - webapi/
    - main.py [ application entry point ]
  - application/
    - ... [ actual application code ] 

2. Run dev server 

    $ export AIO_APP_PATH=webapi/
    $ adev runserver

3. Make any changes on files inside webapi/, works as expected
4. Make any changes on files inside application/, doesn't work

Edit: Currently i am using runserver by directly editing ```runserver/config.py```

**Comment by samuelcolvin** [comment]
Just run across this too, if `--root` is provided it should be used as the base directory to watch.

**Comment by wiryonolau** [comment]
I have a application that monitor a system and running aiohttp at the same time.
Project structure are like this

```bash
root
 |- __main__.py
 |- service.py
 |- container.py
 |- worker.py
 |- http
    |- app.py
    |- action.py
    |- asset
      |- *.js
      |- *.css
    |- view
      |- *.j2
```

The __main__.py will run all registered event loop ( not only aiohttp )

app.py
```python
from aiohttp_devtools import runserver

app = web.Application()
config = runserver.config.Config({
  app_path="root/http"
  root_path="root",
  livereoload=True
})
runserver.serve.modify_main_app(app, config)
```

worker.py
```python
from app import app

async def httpserver():
  runner = web.AppRunner(app)
  await runner.setup()
  site = web.TCPSite(runner, host, port)
  await site.start()

async def other_long_task():
 await long_task()
```

__main__.py
```python
loop = asyncio.get_event_loop()
asyncio.ensure_future(httpserver())
asyncio.ensure_future(other_long_task())
loop.run_forever()
```

With this approached all modified css js or template will be updated on next reload
But if I change python file such as action.py or service.py it will not update.
Is there a way to include python file ?

**Comment by wiryonolau** [comment]
Working example of combining aiohttp with other asyncio operation

```bash
prj
  prj
    |- app.py
    |- __main__.py
    |- __init__.py
    |- service.py
    |- container.py
    |- worker.py
    |- http
       |- app.py
       |- action.py
       |- asset
          |- *.js
          |- *.css
       |- view
          |- *.j2
```

http.app.py
```python
from aiohttp import web

app = web.Application()
# any aiohttp setup here, e.g routes middleware etc
```

worker.py
```python
from app import app

async def httpserver():
   runner = web.AppRunner(app)
   await runner.setup()
   site = web.TCPSite(runner, host, port)
   await site.start()

async def other_long_task():
   while True:
     await long_task()
   await asyncio.sleep(1)
```

\_\_main\_\_.py
run using "**python -m project**" 
```python
from  worker import httpserver, other_long_task

if __name__ == "__main__":
  loop = asyncio.get_event_loop() 
  asyncio.ensure_future(httpserver())
  asyncio.ensure_future(other_long_task())
  loop.run_forever()
```

app.py
run using "**adev runserver project**"
```python
from http.app import app
from worker import other_long_task

def app():
   asyncio.ensure_future(other_long_task())
   return app
```

**Comment by Dreamsorcerer** [comment]
That's still less robust than the approach I described. We also generally discourage using globals like that (if you look at the demos/tutorials for aiohttp, the app object is always local to a function, never a global).

My suggestion would look roughly more like:

`__main__.py`:
```
from my_app.app import init_app

def main() -> None:
    """Run the server in production environment."""
    app = init_app()
    web.run_app(app)


if __name__ == "__main__":
    main()
```

`app.py`:
```
def init_app() -> web.Application:
    """Initialise the web app."""
    app = web.Application()

    setup_routes(app)
    setup_middlewares(app)

    return app

async def create_app() -> web.Application:
    """Create the app for local use.

    Called when running locally through aiohttp-devtools.
    """
    from my_app import _localdev as dev

    app = init_app()
    dev.configure_app(app)

    return app
```

And somewhere add the background task with a cleanup_ctx:
```
async def run_server(_app):
    task = await asyncio.create_task(other_long_task())

    yield

    task.cancel()

app.cleanup_ctx.append(run_server)
```

Your current implementation will be more brittle as the lifetime of the other task is not being controlled by the app. Using a cleanup_ctx like this ensures that the tasks is created and torn down along with the app. As mentioned before, the app should be handling the overall running of the program (using `aiohttp.web.run_app()` rather than messing with low-level asyncio details).

**Comment by Dreamsorcerer** [comment]
I think as mentioned above, the solution to the original issue is to use `--root'. Please reopen if that is not the case.

**Comment by wiryonolau** [comment]
I haven't try --root options, currently it works using the approach you mention using separate file

**Comment by Dreamsorcerer** [comment]
I think there are 2 slightly different cases. The case for `--root` is, for example, when you essentially have 2 applications, so the entry point is one directory, and the local code then spawns the other application in a new process. So, one project I have looks like:

root/
  main_app/
  auxiliary_app/

devtools runs main_app, and my local code spawns auxiliary_app in another process (they would be separate servers in production). By default, devtools would only watch for changes in main_app/, so in this case `--root` can be used to move the watched directory to root/, causing the reload to happen when either app is modified.
