### ISSUE TITLE
runserver not finding main 

### ISSUE THREAD

**Issue by daredevil82** [aio-libs/aiohttp-devtools#219]
* **aiohttp-devtools version:**
0.1.1
* **aiohttp version:**
3.4.4
* **python version:**
3.6.4
* **Platform:**
docker alpine

### Issue Summary
 Error: No name supplied and no default app factory found in main.py with command `command: adev runserver --livereload --port 9701 api/main.py`

### Steps to reproduce

project structure:

```
service
    api
       __init__
       main.py
       routes.py
       views.py
```

```async def init(conf):
    app = web.Application()
    app['config'] = conf
    setup_routes(app)
    return app


def main():
    logging.basicConfig(level=logging.DEBUG)
    app = init(settings)
    web.run_app(app, host=settings.HOST, port=settings.PORT)


if __name__ == '__main__':
    main()```

in `api/main.py`

**Comment by samuelcolvin** [comment]
`init` isn't one of the [default](https://github.com/aio-libs/aiohttp-devtools/blob/master/aiohttp_devtools/runserver/config.py#L19-L24) "guessed" names of the app factory.

use `create_app` as as the function/coroutine name or use the `--app-factory` argument.
