### ISSUE TITLE
Slimming down the package for use in other projects

### ISSUE THREAD

**Issue by pauleveritt** [aio-libs/aiohttp-devtools#222]
Summary: Make aiohttp-devtools as small as possible and move responsibility to other places.

I use the Python [python-livereload](https://github.com/lepture/python-livereload) package a lot, sometimes in the context of other projects. Its watching isn't as scalable as watchgod. I'm interested in an alternative to add to my own project, but I don't want to drag in Jinja2 and I'm not interested in a custom cli "new project" functionality.

OTOH, this package is `aiohttp-devtools` not `aiohttp-livereload` so it kind of advertises as a broader entry point for aiohttp.

Note: I discussed this with Samuel in email. He said "I would consider removing jinja as a dependency of aiohttp-devtools and just simplifying the cookiecutter command a lot to have no options."

**Comment by samuelcolvin** [comment]
Other people have (understandably) also complained about `Jinja` being installed too, we could also remove `isort` if we simplified `start` and make start much more maintainable.

I would guess (based on very little except the issues submitted) that the `start` command gets very little usage compared to `runserver` and `serve`.
