### ISSUE TITLE
reload not working for official quickstart sample on windows

### ISSUE THREAD

**Issue by NewUserHa** [aio-libs/aiohttp-devtools#229]
1111.py
```
from aiohttp import web

async def hello(request):
    return web.Response(text="Hello, world")

app = web.Application()
app.add_routes([web.get('/', hello)])
web.run_app(app)
```
adev runserver 1111.py

then:
modify "Hello, world"

refresh 127.0.0.1, noting change.

**Comment by NewUserHa** [comment]
if comment `web.run_app(app)`, it work as expect. But:
```
[35m[23:01:49][0m[32m Starting aux server at http://localhost:8001 ◆[0m
[35m[23:01:49][0m[32m Starting dev server at http://localhost:8000 ●[0m
[35m[23:02:10][0m [34m●[0m [0mGET / 200 166B 0ms[0m
[35m[23:02:10][0m [34m●[0m [0mGET / 200 166B 0ms[0m
...
```

**Comment by samuelcolvin** [comment]
No way around this in aiohttp-devtools.

moved to https://github.com/aio-libs/aiohttp/issues/3775

**Comment by NewUserHa** [comment]
please notice the new comment.

and could please add the solution to devtools' document to improve?

**Comment by NewUserHa** [comment]
@samuelcolvin

**Comment by samuelcolvin** [comment]
PR welcome to add a comment.

**Comment by NewUserHa** [comment]
@samuelcolvin ok, but I meant the garbled text of `adev` stdout in the second reply.
