### ISSUE TITLE
Cleanup contexts not fully run on ctrl-c

### ISSUE THREAD

**Issue by Yarn** [aio-libs/aiohttp-devtools#252]
* **aiohttp-devtools version:0.13.1**
* **aiohttp version:3.6.2**
* **python version:3.7.6**
* **Platform:MacOS 10.15.2**

### Issue Summary
Cleanup contexts aren't run to completion when exiting `adev runserver` with ctrl-c. They are run correctly when the server is reloaded after a code change.

### Steps to reproduce
Run the following server with `adev runserver` then exit it with ctrl-c. For me it prints x but not y. It prints x and y when auto restarting the server or running the file without adev.

```py
from aiohttp import web
import asyncio

async def ctx(app):
    yield
    print('x')
    await asyncio.sleep(1)
    print('y')

async def handle(request):
    return web.Response(body="test")

app = web.Application()
app.add_routes([
    web.get('/', handle),
])
app.cleanup_ctx.append(ctx)

def main():
    web.run_app(app)

if __name__ == '__main__':
    main()
```

**Comment by samuelcolvin** [comment]
Thanks for reporting, PR welcome to fix this.

**Comment by Dreamsorcerer** [comment]
This has been frustrating me for a while, as it doesn't even close the process correctly, leaving the terminal hanging.

I've had a dig around, and found a trivial fix in the linked PR.
