### ISSUE TITLE
livereload attempts reloads on transient (hidden) temp files

### ISSUE THREAD

**Issue by jmcaine** [aio-libs/aiohttp-devtools#257]
* **aiohttp-devtools version: 0.13.1**
* **aiohttp version: 3.5.4**
* **python version: 3.7.6**
* **Platform: Debian Linux**

### Issue Summary
livereload attempts to reload files on which change detection occurs (watch.py: AppTask:_run).  However, many IDEs and editors save transient autosave/rescue/swap files.  These files may be detected, triggering this code to reload the file, but then the file is gone by the time of the call to src_reload -> Path(), which results in this traceback:

```
Traceback (most recent call last):
  File "/home/jmcaine/dev/projects/aiohttp-sqlite-dominate-stack-reference/aiohttp-devtools/aiohttp_devtools/runserver/watch.py", line 72, in _run
    await src_reload(self._app, f)
  File "/home/jmcaine/dev/projects/aiohttp-sqlite-dominate-stack-reference/aiohttp-devtools/aiohttp_devtools/runserver/serve.py", line 160, in src_reload
    path = str(Path(app['static_url']) / Path(path).relative_to(app['static_path']))
  File "/usr/lib/python3.7/pathlib.py", line 885, in relative_to
    to_drv, to_root, to_parts = self._parse_args(other)
  File "/usr/lib/python3.7/pathlib.py", line 653, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Steps to reproduce
This is difficult to reproduce, obviously, but happens very frequently under the right conditions (99% of the time is achievable, in fact).

### Suggestions
Some ideas might include:

1. a --live-reload-ignore-hidden flag that results in a check: if a file starts with a '.', then it's not reloaded?

2. a filesystem check, to see if the file really exists right before the call to pathlib?  This won't work reliably, though, as the file might stick around to the very last minute.  So, better...

3. an exception handler in serve.py, to catch the TypeError, check that it's this problem, and then quietly go on, rather than dying, since the file didn't want a reload after all.

At the very least, documentation should probably indicate that one might want to set their editor/IDE to store temp swap files somewhere other than right next to the source files themselves (default); most probably have a setting like this.  Kate does.

**Comment by samuelcolvin** [comment]
watchgod already tries to skip common temporary files, see [here](https://github.com/samuelcolvin/watchgod/blob/be319f3abc13117c57ab7313daf618edf33703d7/watchgod/watcher.py#L77)

The simplest solution would probably be a PR to watchgod to exclude the ephemeral files your IDE is creating. Which IDE are you using and what's the path of those file extensions?

btw, it's useful when including code or tracebacks in issues to use triple back quotes to make it easier to read.

**Comment by jmcaine** [comment]
Wow, such a quick reply.  Thank you.  I didn't notice watchgod - good to know.  It may be that it's missing this phantom file because of its ephemerality. I use Kate.  The files that I see are named like this: ".<blah>.py.kate-swp" -- <blah> is the placeholder for the python file to which it might correspond.  Of course, as soon as I save that file, this one gets temporarily saved, presumably to swap with the backup file.  That's the same instant that livereload engages, of course, as it should be.

**Comment by samuelcolvin** [comment]
makes sense, try modifying watchgod and see if it fixes it.

You might try changing that line to:

```py
ignored_file_regexes = r'\.py[cod]$', r'\.___jb_...___$', r'\.(?:\w+-)?sw.$', '~$'
```
(just adding an optional extra group to one of the existing regexes)

**Comment by jmcaine** [comment]
Yes, that worked.  Thank you!

**Comment by samuelcolvin** [comment]
No problem.

Can you submit a pull request to watchgod to fix it?
