### ISSUE TITLE
Middlewares get overriden by debugtoolbar.

### ISSUE THREAD

**Issue by Dreamsorcerer** [aio-libs/aiohttp-devtools#260]
If the middlewares are setup during the app creation (the standard approach given in examples), then aiohttp-devtools ends up appending the debugtoolbar middleware to the end of the list.

This causes a problem as middlewares that depend on handling exceptions no longer run, as the exceptions are caught by debugtoolbar first.

A simple solution may be to insert debugtoolbar at the front of the list, rather than appending it. However, it would be nice to have a mechanism to choose whether a middleware comes before or after debugtoolbar.
    The one exception I have, is a catch-all middleware to display a 500 page. This would need to be before debugtoolbar in the list, so that debugtoolbar can handle the exception when running locally. But, I could potentially just disable that single middleware when running locally, as a workaround.

**Comment by samuelcolvin** [comment]
I stopped using debugtoolbar ages ago as it seemed to be unmaintained, unless a lot of work has been done on it, we might be best to remove it altogether.

**Comment by Dreamsorcerer** [comment]
Even if it's unmaintained, I'm still finding atleast the error display useful. It's a nicer display of exceptions, and there is a button that gives you an interactive terminal directly in that context, so you can see what variables were defined etc. Very useful for debugging, particularly when there's multiple steps needed to reproduce the error.

**Comment by Dreamsorcerer** [comment]
OK, I've switched to enabling it manually, which gives enough control to fix the problem. So, maybe removing it from devtools is fine, and just recommend explicitly setting it up in the code instead.
