### ISSUE TITLE
Import error while starting app

### ISSUE THREAD

**Issue by drsherlock** [aio-libs/aiohttp-devtools#261]
* **aiohttp-devtools version:**
0.13.1
* **aiohttp version:**
3.6.2
* **python version:**
3.7.3
* **Platform:**
MacOS

### Issue Summary
Trying to run the app with `adev runserver my-app/app.py`. But I am getting this error `Error: error importing "my-app.app" from "/Users/drsherlock/Extra/python/MyApp": No module named 'config'`

### Steps to reproduce
Here is the code snippet from app.py - 

```
from aiohttp import web

from config.development import config
from routes import setup_routes

async def init_app(argv=None):
    app = web.Application()
    setup_routes(app)
    return app

def main(argv):
    app = init_app(argv)
    web.run_app(app,
                host=config['SERVER_HOST'],
                port=config['SERVER_PORT'])
```

**Comment by Dreamsorcerer** [comment]
Looks like the PATH is not configured correctly to find your imports.

I recall iterating through a couple of different import methods while trying to get several tools to play nice with my app. The approach I've settled on is a module structure. So, imports look like:
`from my_application.routes import setup_routes`
I can then run locally with `adev runserver my_application`, and run normally (for production) with `python3 -m my_application`.

Hope that's helpful, if you've still not figured out how to get it working.

**Comment by drsherlock** [comment]
Could not get this working. Ended up using nodemon and it works perfectly.
Thank you though.
