### ISSUE TITLE
[feature-request] Adding additional parameters

### ISSUE THREAD

**Issue by brean** [aio-libs/aiohttp-devtools#267]
When I run adev with custom parameters that I like to use in my server application (lets say --db_host to specify a database hostname) I get the error message: 
```
Error: no such option: --db_host
```
So I am not able to use argparse to get this parameter. So I think for additional parameters there should be a way to whitelist them.

**Comment by Dreamsorcerer** [comment]
I think I'll be needing this too. It looks like the click library being used by this project supports this:
https://click.palletsprojects.com/en/7.x/advanced/#forwarding-unknown-options

So, maybe it just needs to grab the extra unknown arguments and overwrite sys.argv with them before loading the app, or something like that.

I might have a go at writing a PR in a couple of weeks (although none of my existing PRs have been merged yet).

**Comment by brean** [comment]
another workaround might be to store everything in system variables and just use os.environ, which would be okay for my case. I run adev in a docker-based environment, with a volume to my code mounted inside the docker container. So my parameters are already exposed as environment variables.
