### ISSUE TITLE
Reload on additional file changes

### ISSUE THREAD

**Issue by Dreamsorcerer** [aio-libs/aiohttp-devtools#269]
It would be nice to specify some other files/directories that should be watched for changes and trigger a reload.

In my use-case, the application spawns a separate Python process from some other file, so changes to that file are not recognised as it is not part of the main application.

Folder structure looks like:
root/main_application/
root/extra_application/

I run `adev runserver main_application`, which itself spawn a process to run extra_application. Changes to extra_application don't cause a reload.

Expected solution, add an option so it is possible to do something like:
`adev runserver main_application --watch extra_application/`

**Comment by diefans** [comment]
I am using https://github.com/eradman/entr for reloading my dev apps and so on....

**Comment by Dreamsorcerer** [comment]
This is a duplicate of #209.

Basically, use `--root` on the parent directory.
