### ISSUE TITLE
Auto reload get triggered by Emacs tmp files

### ISSUE THREAD

**Issue by Randomneo** [aio-libs/aiohttp-devtools#279]
* **aiohttp-devtools version: 0.13.1**
* **aiohttp version: 3.7.2**
* **python version: Python 3.8.6**
* **Platform:**
    5.9.2-arch1-1
    Distributor ID: Arch
    Description:    Arch Linux

### Issue Summary

Auto reload get triggered by Emacs tmp files. It would be nice to have ability to set regex excludes for such auto-reload. 

### Steps to reproduce

Create hello world project.

Edit main.py (or any other name) with emacs (don't save edited file)

Got error:

    error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/opt/project/.#main.py'

Info about file

    $ file .\#main.py
    .#main.py: broken symbolic link to username@pc-name.6945:1604093602

Its a bit tricky file (that exists and do not, so you got this problem). I suppose this error shouldn't be shown at list for files like .#*.

**Comment by qJ6Fvq** [comment]
samuelcolvin/watchgod#70

**Comment by Dreamsorcerer** [comment]
Looks like this is fixed upstream. Please reopen if still an issue with v1.0.
