### ISSUE TITLE
Not working with python 3.10 version

### ISSUE THREAD

**Issue by qerdcv** [aio-libs/aiohttp-devtools#390]
* **aiohttp-devtools version:**
* aiohttp-devtools==0.13.1
* **aiohttp version:**
* aiohttp==3.8.1
* **python version:**
* Python 3.10.0
* **Platform:**
* macOS 12.1 21C52 arm64

### Issue Summary

TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary
### Steps to reproduce
* Install python 3.10
* Create simple aiohttp server
* try to run with adev runserver

**Comment by Dreamsorcerer** [comment]
Duplicate #389

**Comment by Dreamsorcerer** [comment]
Released now. Should be working with 3.10, but the test are failing currently (#376), so let me know if there are any issues.
