### ISSUE TITLE
Removed method load_settings() in prepare_database()

### ISSUE THREAD

**Issue by einarsnow** [aio-libs/aiohttp-devtools#48]
``make reset-database`` returned:
```
from .main import load_settings, pg_dsn
ImportError: cannot import name 'load_settings'
```

**Comment by samuelcolvin** [comment]
Sorry about that, I've created a PR to fix in the mean time if you wanted a fixed version you can copy [this](https://github.com/aio-libs/aiohttp-devtools/blob/fix-db-reset/aiohttp_devtools/start/template/app/management.py) into the new project.

**Comment by samuelcolvin** [comment]
No problem, I generally leave such issues open and let them be automatically be closed as the PR is merged. Thanks for reporting.
