### ISSUE TITLE
Looking to wrong server to find static files.

### ISSUE THREAD

**Issue by leveraction** [aio-libs/aiohttp-devtools#533]
* **aiohttp-devtools version:**--1.0.post0
* **aiohttp version:**---3.8.4
* **python version:**: ---3.8
* **Platform:** Ubuntu 22

### Start the dev server with 
 "adev runserver ./application.py"
 This starts two servers running on ports 8000 and 8001
 Using the 8000 version, page loads but without static assets.
 Network calls indicate that calls for static assets are being made to the correct address but on the 8000 server.
I thought the idea was to essentially mock a static web server with the second (8001) server and serve static assets. I though calls were going to somehow be redirected to the second (8001) server.
I feel like there may be something obvious that I am missing.
Thanks.

**Comment by leveraction** [comment]
OK, I think I fixed it.  For the next guy:
You have to tell aiohttp about the static routes manually. 
So, wherever you add your routes add the following:
Example: 
app.add_routes([web.static('/prefix', path_to_static_folder)])

so in my particular case...
app.add_routes([web.static('/outpost/static', './static')])

Also see:
https://docs.aiohttp.org/en/stable/web_advanced.html#static-file-handling

**Comment by Dreamsorcerer** [comment]
Yes, you probably need to ensure you create a static route in aiohttp in order for it to work. You'd then use that router to generate URLs dynamically, rather than using hardcoded paths.
