### ISSUE TITLE
[feature request] Passing arguments to app from CLI

### ISSUE THREAD

**Issue by madduck** [aio-libs/aiohttp-devtools#707]
* **aiohttp-devtools version:** 1.1.2
* **aiohttp version:** 3.11.11
* **python version:** 3.12.8
* **Platform:** Linux

### Issue Summary

This isn't an "issue", more a feature request. Could the `adev` CLI possibly forward unknown command-line arguments, or maybe even better — all arguments following `--` on the CLI, to the app somehow?

For instance:

```
adev runserver webserver.py --app-factory create_app --port 8080 --host :: -- -d /tmp/db
```

in this case, maybe "`-d /tmp/db`" could be made available somehow, possibly even by writing it to `sys.argv`. Because then my app's own `argparse` or `click` parsing would just keep working.

**Comment by Dreamsorcerer** [comment]
It does (maybe it's only positional?):
https://github.com/aio-libs/aiohttp-devtools/blob/649b2c86419b41a576cc490815b4971e8a39a6de/aiohttp_devtools/cli.py#L97

Feel free to make a PR if there's something else to do there.

**Comment by madduck** [comment]
Yes, this only works for positional arguments:

```
% adev runserver webserver.py --app-factory create_app --port 8080 --host :: -t
Usage: adev runserver [OPTIONS] [APP_PATH] [PROJECT_ARGS]...
Try 'adev runserver --help' for help.

Error: No such option: -t
```

I'll have to dive into `click` to see how to best handle `--`.

**Comment by madduck** [comment]
Turns out `--` already works out of the box. Sorry, I must have done something else wrong while testing.
