### ISSUE TITLE
Does runserver work with uvloop?

### ISSUE THREAD

**Issue by imbolc** [aio-libs/aiohttp-devtools#86]
I tried different ways but always got `attached to a different loop` exception

**Comment by samuelcolvin** [comment]
There's no reason why devtools shouldn't work with uvloop, but it's generally unnecessary since devtools should only be used for development where performance isn't important.

Any do you need uvloop?

What did you do to try and use it?

**Comment by imbolc** [comment]
I'm sorry, can't reproduce this error in a simple app. I think there is some mess with loops in own my code.
