### ISSUE TITLE
Expose __version__ in __init__.py

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-devtools#98]
Looks like it is standard de-facto for python packaging.

**Comment by kxepal** [comment]
I was thought that `pkg_resources.get_distribution(...).version` is a bit more reliable and common than magic attributes.

**Comment by asvetlov** [comment]
You could use `pkg_resources` on your own but supporting `aiohttp_devtools.__version__` attribute doesn't make things worse.
Also we do it for every *aio-libs* library -- let's be consistent.

**Comment by asvetlov** [comment]
Well, maybe not for every lib -- I didn't check it. But for most of them at least.

**Comment by kxepal** [comment]
Hm, ok. Took a note for aiocouchdb.

**Comment by samuelcolvin** [comment]
I normally do this, I think I just forgot, will fix.
