### ISSUE TITLE
Expose command line interface in __init__.py

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp-devtools#99]
`python3 -m aiohttp_devtools <args>` should work in the same way as `adev <args>`.

See also https://stackoverflow.com/questions/44820398/how-to-run-adevaiohttp-devtools-command-using-pycharm

**Comment by samuelcolvin** [comment]
Makes sense, should be trivial.

**Comment by samuelcolvin** [comment]
Ok, I've added `__main__.py` but pycharm's support for stuff like this is very poor and that doesn't actually allow you to use `aiohttp_devtools` with pycharm debug. I'll describe how to do that on SO.
